package po;

public class TBizTopic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BIZ_TOPIC.topic_id
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BIZ_TOPIC.autor_id
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    private Integer autorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BIZ_TOPIC.topic_cate
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    private String topicCate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BIZ_TOPIC.img_addr
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    private String imgAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BIZ_TOPIC.pub_time
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    private String pubTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BIZ_TOPIC.update_time
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BIZ_TOPIC.content
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BIZ_TOPIC.topic_id
     *
     * @return the value of T_BIZ_TOPIC.topic_id
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BIZ_TOPIC.topic_id
     *
     * @param topicId the value for T_BIZ_TOPIC.topic_id
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BIZ_TOPIC.autor_id
     *
     * @return the value of T_BIZ_TOPIC.autor_id
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public Integer getAutorId() {
        return autorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BIZ_TOPIC.autor_id
     *
     * @param autorId the value for T_BIZ_TOPIC.autor_id
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public void setAutorId(Integer autorId) {
        this.autorId = autorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BIZ_TOPIC.topic_cate
     *
     * @return the value of T_BIZ_TOPIC.topic_cate
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public String getTopicCate() {
        return topicCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BIZ_TOPIC.topic_cate
     *
     * @param topicCate the value for T_BIZ_TOPIC.topic_cate
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public void setTopicCate(String topicCate) {
        this.topicCate = topicCate == null ? null : topicCate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BIZ_TOPIC.img_addr
     *
     * @return the value of T_BIZ_TOPIC.img_addr
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BIZ_TOPIC.img_addr
     *
     * @param imgAddr the value for T_BIZ_TOPIC.img_addr
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr == null ? null : imgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BIZ_TOPIC.pub_time
     *
     * @return the value of T_BIZ_TOPIC.pub_time
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public String getPubTime() {
        return pubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BIZ_TOPIC.pub_time
     *
     * @param pubTime the value for T_BIZ_TOPIC.pub_time
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public void setPubTime(String pubTime) {
        this.pubTime = pubTime == null ? null : pubTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BIZ_TOPIC.update_time
     *
     * @return the value of T_BIZ_TOPIC.update_time
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BIZ_TOPIC.update_time
     *
     * @param updateTime the value for T_BIZ_TOPIC.update_time
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BIZ_TOPIC.content
     *
     * @return the value of T_BIZ_TOPIC.content
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BIZ_TOPIC.content
     *
     * @param content the value for T_BIZ_TOPIC.content
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}