package mapper;

import po.TBizTopic;

public interface TBizTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BIZ_TOPIC
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    int deleteByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BIZ_TOPIC
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    int insert(TBizTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BIZ_TOPIC
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    int insertSelective(TBizTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BIZ_TOPIC
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    TBizTopic selectByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BIZ_TOPIC
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    int updateByPrimaryKeySelective(TBizTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BIZ_TOPIC
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TBizTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BIZ_TOPIC
     *
     * @mbg.generated Tue Jun 25 16:14:32 CST 2019
     */
    int updateByPrimaryKey(TBizTopic record);
}